# This is a basic workflow to help you get started with Actions

name: gobfuscator-frp

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  frpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - run: |
          # https://github.com/actions/setup-go/issues/107
          cp -f `which go` /usr/bin/go
      - uses: actions/checkout@v2
      - name: build gobfuscator
        run: go env && go build -o gobfuscator .
      - name: clone frp
        run: cd /tmp && git clone https://github.com/fatedier/frp.git && cd frp && sed -i 's/go build/\.\/gobfuscator build/g' Makefile
      - name: obfuscate frp
        run: go env && cp gobfuscator /tmp/frp/gobfuscator && cd /tmp/frp && make build
