# This is a basic workflow to help you get started with Actions

name: gobfuscator-fscan

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fscan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dependency
        run: rm -rf /usr/local/go && curl https://dl.google.com/go/go1.16.4.linux-amd64.tar.gz -o go1.16.4.linux-amd64.tar.gz && tar -xzf go1.16.4.linux-amd64.tar.gz
      - name: build gobfuscator
        run: export PATH=`pwd`/go/bin:$PATH && export GOROOT=`pwd`/go && git clone https://github.com/pinohans/gobfuscator.git && cd gobfuscator && go mod tidy && go build -o gobfuscator .
      - name: clone fscan
        run: git clone https://github.com/shadow1ng/fscan.git
      - name: obfuscate fscan
        run: export PATH=`pwd`/go/bin:$PATH && export GOROOT=`pwd`/go && cd gobfuscator && echo '{"MainPkgDir":"../fscan","OutputPath":"./fscan","NewGopath":"pkg","Tags":"","GOOS":"windows","GOARCH":"amd64","CGOENABLED":"0","WindowsHide":"1","NoStatic":"1"}' > config.json && ./gobfuscator -c config.json
